server:
  port: ${mvtalker.server.port}

spring:
  profiles:
    active: prod
  application:
    name: webrtc-service

  cloud:
    # 配置 Nacos 注册中心的地址
    nacos:
      discovery:
        server-addr: ${mvtalker.nacos.config.server-addr}
        # namespace: dev
        # group: DEFAULT_GROUP
        # file-extension: yaml # 指定配置文件后缀
        # shared-configs: # 全局共享配置（低优先级）
        #  - data-id: shared-jdbc.yaml
        #    refresh: true
        #  - data-id: shared-log.yaml
        #    refresh: true

    # 配置 Sentinel 的地址
    sentinel:
      transport:
        dashboard: ${mvtalker.sentinel.transport.dashboard}
      # http-method-specify: true # 启用对 HTTP 方法的区分

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: TRACE
    root: INFO
    com.mvtalker.webrtc: DEBUG
    com.mvtalker.utilities: DEBUG  # 覆盖工具模块的包
    com.mvtalker.utilities.interceptor: DEBUG # 或者更精确到拦截器包
  pattern:
    dateformat: HH:mm:ss:SSS

feign:
  client:
    config:
      user-service:
        connectTimeout: 3000    # 连接超时3秒
        readTimeout: 5000       # 读取超时5秒
        loggerLevel: basic      # 日志级别
  circuit breaker:
    enabled: true               # 启用熔断
  # 开启连接池
  okhttp:
    enabled: true
  # 让微服务之间的请求调用也能被Sentinel追踪
  sentinel:
    enabled: true

jwt:
  # 密钥
  secret: ${mvtalker.jwt.secret-key}
  # 令牌过期时间，单位为毫秒
  expiration-time: 604800000 # 7天
