# 该文件将被Git忽略，防止敏感数据公开暴露
mvtalker:
  db:
    host: localhost
    port: 3306
    database: community_db
    user: backend_user
    password: backend123
  jwt:
    secret-key: 6F4HDKtcFUYLdyEaJ9gk5ic9wW3ayCUEVcwNG2TI3ms=