server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # namespace: dev
        # group: DEFAULT_GROUP
    gateway:
      # 路由配置
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**

        #- id: user-service
        #  uri: lb://user-service
        #  predicates:
        #    - Path=/user/**

jwt:
  # 密钥
  secret: MySecretKey
  # 令牌过期时间，单位为毫秒
  expiration-time: 3600000
  # 排除的路径
  exclude-paths:
    - /user/login
