server:
  port: 8080

spring:
  profiles:
    active: dev
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        # namespace: dev
        # group: DEFAULT_GROUP
    gateway:
      # 路由配置
      routes:
        # WebSocket专用路由（需置于最前）
        - id: webrtc-websocket
          uri: lb://webrtc-service
          predicates:
            - Path=/webrtc/**
            - Header=Upgrade, websocket

        - id: user-service
          uri: lb://user-service # 指定要转发到哪个微服务，lb表示负载均衡
          predicates:
            - Path=/user/**

        - id: community-service
          uri: lb://community-service
          predicates:
            - Path=/community/**
#        - id: webrtc-service
#          uri: lb://webrtc-service
#          predicates:
#            - Path=/webrtc/**

logging:
  level:
    logging:
      level:
        root: INFO
        com.mvtalker: DEBUG
        org.springframework.cloud.gateway: DEBUG  # 关键！开启网关DEBUG日志
        org.springframework.web.socket: DEBUG     # WebSocket相关日志
        org.springframework.http.server.reactive: DEBUG  # HTTP请求处理
        org.springframework.web.reactive.socket: DEBUG   # WebSocket升级处理

jwt:
  # 密钥
  secret: ${mvtalker.jwt.secret-key}
  # 令牌过期时间，单位为毫秒
  expiration-time: 604800000 # 7天

gateway:
  jwt:
    # 排除的路径，这是网关层特有的JWT配置
    exclude-paths:
      - /user/login
      - /user/register
